services:
  rstudio_environment:
    image: rocker/rstudio:4.1.3
    ports:
      - "8888:8787"
    volumes:
      - .:/home/rstudio/introduction-to-datascience
    environment:
      # PASSWORD: asdf
      DISABLE_AUTH: true


## Docker compose allows us to add in information of a particular docker image
## we can add in more than one image in this docker compose and assign different ports
## this is an intro to container orchestration

## run docker-compose up -d